[theme]
primaryColor = "#6a9fb5"           # Soft blue for primary elements
backgroundColor = "#f0f4f8"         # Light background color
secondaryBackgroundColor = "#ffffff" # White for secondary elements
textColor = "#333333"               # Dark gray text for readability
font = "sans serif"                 # Generic font type; Poppins will be imported in styling.
